name: build-and-publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # (facoltativo) rigenera ogni lunedì alle 03:00

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # consente di pushare su gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # buona pratica per le build

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 🔹 Render del sito
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      # 🔹 Pubblica su gh-pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
