name: build-and-publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # (opzionale) rigenera ogni lunedì 03:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: quarto-dev/quarto-actions/render@v2
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
